import { Translations } from "./i18n/translatable";

// The official holidays' titles (Lib/publicHolidaySeed.ts, Lib/lunarHolidays.ts)
// in the site's other languages, so the calendars of a doctor or a patient
// who reads English, Arabic, ... are not in Persian. A day with two occasions
// joins them with " · " and is translated part by part.
type Row = Record<"en" | "ar" | "ur" | "tr" | "de" | "fr" | "es" | "pt" | "ru" | "zh" | "ja" | "hi" | "bn" | "id", string>;

const TITLES: Record<string, Row> = {
  "عید نوروز": { en: "Nowruz", ar: "عيد النوروز", ur: "عید نوروز", tr: "Nevruz Bayramı", de: "Nouruz", fr: "Norouz", es: "Nouruz", pt: "Nowruz", ru: "Навруз", zh: "诺鲁孜节", ja: "ノウルーズ", hi: "नौरोज़", bn: "নওরোজ", id: "Nowruz" },
  "روز جمهوری اسلامی": { en: "Islamic Republic Day", ar: "يوم الجمهورية الإسلامية", ur: "یومِ جمہوریہ اسلامی", tr: "İslam Cumhuriyeti Günü", de: "Tag der Islamischen Republik", fr: "Jour de la République islamique", es: "Día de la República Islámica", pt: "Dia da República Islâmica", ru: "День Исламской Республики", zh: "伊斯兰共和国日", ja: "イスラム共和国の日", hi: "इस्लामी गणराज्य दिवस", bn: "ইসলামি প্রজাতন্ত্র দিবস", id: "Hari Republik Islam" },
  "روز طبیعت": { en: "Nature Day", ar: "يوم الطبيعة", ur: "یومِ فطرت", tr: "Doğa Günü", de: "Tag der Natur", fr: "Jour de la nature", es: "Día de la Naturaleza", pt: "Dia da Natureza", ru: "День природы", zh: "自然日", ja: "自然の日", hi: "प्रकृति दिवस", bn: "প্রকৃতি দিবস", id: "Hari Alam" },
  "رحلت امام خمینی": { en: "Death of Imam Khomeini", ar: "ذكرى رحيل الإمام الخميني", ur: "امام خمینی کی رحلت", tr: "İmam Humeyni'nin vefatı", de: "Todestag von Imam Chomeini", fr: "Décès de l'imam Khomeini", es: "Muerte del imán Jomeini", pt: "Morte do Imã Khomeini", ru: "Годовщина смерти имама Хомейни", zh: "霍梅尼逝世纪念日", ja: "ホメイニ師逝去の日", hi: "इमाम ख़ुमैनी की पुण्यतिथि", bn: "ইমাম খোমেনির মৃত্যুবার্ষিকী", id: "Wafatnya Imam Khomeini" },
  "قیام ۱۵ خرداد": { en: "15 Khordad Uprising", ar: "انتفاضة 15 خرداد", ur: "۱۵ خرداد کی بغاوت", tr: "15 Hordad Ayaklanması", de: "Aufstand vom 15. Chordād", fr: "Soulèvement du 15 Khordad", es: "Levantamiento del 15 de Jordad", pt: "Revolta de 15 de Khordad", ru: "Восстание 15 хордада", zh: "霍尔达德月15日起义纪念日", ja: "ホルダード月15日蜂起の日", hi: "15 ख़ुरदाद विद्रोह", bn: "১৫ খোরদাদ অভ্যুত্থান", id: "Pemberontakan 15 Khordad" },
  "پیروزی انقلاب اسلامی": { en: "Islamic Revolution Victory Day", ar: "ذكرى انتصار الثورة الإسلامية", ur: "اسلامی انقلاب کی کامیابی کا دن", tr: "İslam Devrimi'nin Zafer Günü", de: "Jahrestag der Islamischen Revolution", fr: "Anniversaire de la révolution islamique", es: "Aniversario de la Revolución Islámica", pt: "Aniversário da Revolução Islâmica", ru: "День победы Исламской революции", zh: "伊斯兰革命胜利纪念日", ja: "イスラム革命勝利記念日", hi: "इस्लामी क्रांति विजय दिवस", bn: "ইসলামি বিপ্লব বিজয় দিবস", id: "Hari Kemenangan Revolusi Islam" },
  "ملی شدن صنعت نفت": { en: "Oil Nationalization Day", ar: "يوم تأميم صناعة النفط", ur: "تیل کی صنعت قومیانے کا دن", tr: "Petrolün Millileştirilmesi Günü", de: "Tag der Verstaatlichung der Ölindustrie", fr: "Jour de la nationalisation du pétrole", es: "Día de la Nacionalización del Petróleo", pt: "Dia da Nacionalização do Petróleo", ru: "День национализации нефтяной промышленности", zh: "石油国有化纪念日", ja: "石油国有化記念日", hi: "तेल राष्ट्रीयकरण दिवस", bn: "তেল জাতীয়করণ দিবস", id: "Hari Nasionalisasi Minyak" },
  "عید سعید فطر": { en: "Eid al-Fitr", ar: "عيد الفطر السعيد", ur: "عید الفطر", tr: "Ramazan Bayramı", de: "Fest des Fastenbrechens (Eid al-Fitr)", fr: "Aïd el-Fitr", es: "Eid al-Fitr", pt: "Eid al-Fitr", ru: "Ураза-байрам", zh: "开斋节", ja: "イード・アル＝フィトル", hi: "ईद-उल-फ़ित्र", bn: "ঈদুল ফিতর", id: "Idulfitri" },
  "تعطیل به مناسبت عید سعید فطر": { en: "Eid al-Fitr holiday", ar: "عطلة عيد الفطر", ur: "عید الفطر کی تعطیل", tr: "Ramazan Bayramı tatili", de: "Feiertag zum Eid al-Fitr", fr: "Congé de l'Aïd el-Fitr", es: "Festivo por Eid al-Fitr", pt: "Feriado de Eid al-Fitr", ru: "Выходной по случаю Ураза-байрама", zh: "开斋节假期", ja: "イード・アル＝フィトルの休日", hi: "ईद-उल-फ़ित्र की छुट्टी", bn: "ঈদুল ফিতরের ছুটি", id: "Libur Idulfitri" },
  "شهادت امام جعفر صادق (ع)": { en: "Martyrdom of Imam Ja'far al-Sadiq", ar: "استشهاد الإمام جعفر الصادق (ع)", ur: "شہادت امام جعفر صادق (ع)", tr: "İmam Cafer-i Sadık'ın şehadeti", de: "Martyrium von Imam Dschafar as-Sadiq", fr: "Martyre de l'imam Ja'far al-Sadiq", es: "Martirio del imán Ja'far al-Sadiq", pt: "Martírio do Imã Ja'far al-Sadiq", ru: "Мученичество имама Джафара ас-Садика", zh: "伊玛目贾法尔·萨迪克殉难日", ja: "イマーム・ジャアファル・サーディク殉教の日", hi: "इमाम जाफ़र सादिक़ की शहादत", bn: "ইমাম জাফর সাদিকের শাহাদাত", id: "Syahidnya Imam Ja'far ash-Shadiq" },
  "عید سعید قربان": { en: "Eid al-Adha", ar: "عيد الأضحى المبارك", ur: "عید الاضحیٰ", tr: "Kurban Bayramı", de: "Opferfest (Eid al-Adha)", fr: "Aïd el-Adha", es: "Eid al-Adha", pt: "Eid al-Adha", ru: "Курбан-байрам", zh: "古尔邦节", ja: "イード・アル＝アドハー", hi: "ईद-उल-अज़हा", bn: "ঈদুল আযহা", id: "Iduladha" },
  "عید سعید غدیر خم": { en: "Eid al-Ghadir", ar: "عيد الغدير الأغر", ur: "عید غدیر", tr: "Gadir-i Hum Bayramı", de: "Ghadir-Fest", fr: "Aïd al-Ghadir", es: "Eid al-Ghadir", pt: "Eid al-Ghadir", ru: "Праздник Гадир", zh: "盖迪尔节", ja: "ガディール・フンムの祝日", hi: "ईद-ए-ग़दीर", bn: "ঈদে গাদির", id: "Idul Ghadir" },
  "تاسوعای حسینی": { en: "Tasua", ar: "تاسوعاء الحسين (ع)", ur: "تاسوعا", tr: "Tasua", de: "Tasua", fr: "Tasua", es: "Tasua", pt: "Tasua", ru: "Тасуа", zh: "塔苏阿日", ja: "タースーアー", hi: "तासुआ", bn: "তাসুয়া", id: "Tasu'a" },
  "عاشورای حسینی": { en: "Ashura", ar: "عاشوراء الحسين (ع)", ur: "عاشورا", tr: "Aşure", de: "Aschura", fr: "Achoura", es: "Ashura", pt: "Ashura", ru: "Ашура", zh: "阿舒拉日", ja: "アーシューラー", hi: "आशूरा", bn: "আশুরা", id: "Asyura" },
  "اربعین حسینی": { en: "Arbaeen", ar: "أربعينية الإمام الحسين (ع)", ur: "اربعین", tr: "Erbain", de: "Arbain", fr: "Arbaïn", es: "Arbaín", pt: "Arbaeen", ru: "Арбаин", zh: "阿尔巴因节", ja: "アルバイーン", hi: "अरबईन", bn: "আরবাঈন", id: "Arbain" },
  "رحلت رسول اکرم (ص) و شهادت امام حسن مجتبی (ع)": { en: "Death of the Prophet Muhammad and martyrdom of Imam Hasan", ar: "رحيل الرسول الأكرم (ص) واستشهاد الإمام الحسن المجتبى (ع)", ur: "رحلتِ رسول اکرم (ص) اور شہادتِ امام حسن مجتبیٰ (ع)", tr: "Hz. Muhammed'in vefatı ve İmam Hasan'ın şehadeti", de: "Todestag des Propheten Muhammad und Martyrium von Imam Hasan", fr: "Décès du Prophète Mahomet et martyre de l'imam Hassan", es: "Muerte del Profeta Mahoma y martirio del imán Hasan", pt: "Morte do Profeta Maomé e martírio do Imã Hasan", ru: "Кончина Пророка Мухаммада и мученичество имама Хасана", zh: "先知穆罕默德逝世及伊玛目哈桑殉难日", ja: "預言者ムハンマド逝去とイマーム・ハサン殉教の日", hi: "पैग़ंबर मुहम्मद का निधन और इमाम हसन की शहादत", bn: "মহানবী (সা.)-এর ওফাত ও ইমাম হাসানের শাহাদাত", id: "Wafatnya Nabi Muhammad dan syahidnya Imam Hasan" },
  "شهادت امام رضا (ع)": { en: "Martyrdom of Imam Reza", ar: "استشهاد الإمام الرضا (ع)", ur: "شہادت امام رضا (ع)", tr: "İmam Rıza'nın şehadeti", de: "Martyrium von Imam Reza", fr: "Martyre de l'imam Reza", es: "Martirio del imán Reza", pt: "Martírio do Imã Reza", ru: "Мученичество имама Резы", zh: "伊玛目礼萨殉难日", ja: "イマーム・レザー殉教の日", hi: "इमाम रज़ा की शहादत", bn: "ইমাম রেজার শাহাদাত", id: "Syahidnya Imam Ridha" },
  "شهادت امام حسن عسکری (ع)": { en: "Martyrdom of Imam Hasan al-Askari", ar: "استشهاد الإمام الحسن العسكري (ع)", ur: "شہادت امام حسن عسکری (ع)", tr: "İmam Hasan Askeri'nin şehadeti", de: "Martyrium von Imam Hasan al-Askari", fr: "Martyre de l'imam Hassan al-Askari", es: "Martirio del imán Hasan al-Askari", pt: "Martírio do Imã Hasan al-Askari", ru: "Мученичество имама Хасана аль-Аскари", zh: "伊玛目哈桑·阿斯卡里殉难日", ja: "イマーム・ハサン・アスカリー殉教の日", hi: "इमाम हसन अस्करी की शहादत", bn: "ইমাম হাসান আসকারির শাহাদাত", id: "Syahidnya Imam Hasan al-Askari" },
  "میلاد رسول اکرم (ص) و امام جعفر صادق (ع)": { en: "Birth of the Prophet Muhammad and Imam Ja'far al-Sadiq", ar: "ميلاد الرسول الأكرم (ص) والإمام جعفر الصادق (ع)", ur: "میلادِ رسول اکرم (ص) و امام جعفر صادق (ع)", tr: "Hz. Muhammed'in ve İmam Cafer-i Sadık'ın doğumu", de: "Geburtstag des Propheten Muhammad und von Imam Dschafar as-Sadiq", fr: "Naissance du Prophète Mahomet et de l'imam Ja'far al-Sadiq", es: "Nacimiento del Profeta Mahoma y del imán Ja'far al-Sadiq", pt: "Nascimento do Profeta Maomé e do Imã Ja'far al-Sadiq", ru: "Рождение Пророка Мухаммада и имама Джафара ас-Садика", zh: "先知穆罕默德及伊玛目贾法尔·萨迪克诞辰", ja: "預言者ムハンマドとイマーム・ジャアファル・サーディク生誕の日", hi: "पैग़ंबर मुहम्मद और इमाम जाफ़र सादिक़ का जन्मदिन", bn: "মহানবী (সা.) ও ইমাম জাফর সাদিকের জন্মদিন", id: "Maulid Nabi Muhammad dan Imam Ja'far ash-Shadiq" },
  "شهادت حضرت فاطمه زهرا (س)": { en: "Martyrdom of Fatimah al-Zahra", ar: "استشهاد السيدة فاطمة الزهراء (س)", ur: "شہادت حضرت فاطمہ زہرا (س)", tr: "Hz. Fatıma'nın şehadeti", de: "Martyrium von Fatima az-Zahra", fr: "Martyre de Fatima al-Zahra", es: "Martirio de Fátima al-Zahra", pt: "Martírio de Fátima al-Zahra", ru: "Мученичество Фатимы аз-Захры", zh: "法蒂玛·扎赫拉殉难日", ja: "ファーティマ・ザフラー殉教の日", hi: "हज़रत फ़ातिमा ज़हरा की शहादत", bn: "হযরত ফাতিমা যাহরার শাহাদাত", id: "Syahidnya Fatimah az-Zahra" },
  "ولادت امام علی (ع) و روز پدر": { en: "Birth of Imam Ali and Father's Day", ar: "ولادة الإمام علي (ع) ويوم الأب", ur: "ولادتِ امام علی (ع) اور یومِ والد", tr: "Hz. Ali'nin doğumu ve Babalar Günü", de: "Geburtstag von Imam Ali und Vatertag", fr: "Naissance de l'imam Ali et fête des pères", es: "Nacimiento del imán Alí y Día del Padre", pt: "Nascimento do Imã Ali e Dia dos Pais", ru: "Рождение имама Али и День отца", zh: "伊玛目阿里诞辰暨父亲节", ja: "イマーム・アリー生誕の日・父の日", hi: "इमाम अली का जन्मदिन और पितृ दिवस", bn: "ইমাম আলীর জন্মদিন ও বাবা দিবস", id: "Kelahiran Imam Ali dan Hari Ayah" },
  "مبعث رسول اکرم (ص)": { en: "Mab'ath (the Prophet's mission)", ar: "المبعث النبوي الشريف", ur: "بعثتِ رسول اکرم (ص)", tr: "Hz. Muhammed'e peygamberlik verilişi (Mebas)", de: "Mabʿath (Berufung des Propheten)", fr: "Mab'ath (mission du Prophète)", es: "Mab'ath (misión del Profeta)", pt: "Mab'ath (missão do Profeta)", ru: "Маб'ас (начало пророческой миссии)", zh: "先知受命日", ja: "預言者召命の日（マブアス）", hi: "मबअस (पैग़ंबर की नबूवत)", bn: "মাবআস (নবুয়ত লাভ)", id: "Mab'ats (pengangkatan Nabi)" },
  "ولادت حضرت قائم (عج) و جشن نیمه شعبان": { en: "Birth of Imam al-Mahdi (Mid-Sha'ban)", ar: "ولادة الإمام المهدي (عج) وعيد النصف من شعبان", ur: "ولادتِ امام مہدی (عج) اور جشنِ نیمہ شعبان", tr: "İmam Mehdi'nin doğumu (Şaban'ın 15'i)", de: "Geburtstag von Imam al-Mahdi (Mitte Schaʿban)", fr: "Naissance de l'imam al-Mahdi (mi-Cha'ban)", es: "Nacimiento del imán al-Mahdi (mitad de Sha'ban)", pt: "Nascimento do Imã al-Mahdi (meio de Sha'ban)", ru: "Рождение имама Махди (середина шаабана)", zh: "伊玛目马赫迪诞辰（舍尔邦月中）", ja: "イマーム・マフディー生誕の日（シャアバーン月中日）", hi: "इमाम महदी का जन्मदिन (मध्य शाबान)", bn: "ইমাম মাহদির জন্মদিন (মধ্য শাবান)", id: "Kelahiran Imam al-Mahdi (Nisfu Sya'ban)" },
  "شهادت امام علی (ع)": { en: "Martyrdom of Imam Ali", ar: "استشهاد الإمام علي (ع)", ur: "شہادت امام علی (ع)", tr: "Hz. Ali'nin şehadeti", de: "Martyrium von Imam Ali", fr: "Martyre de l'imam Ali", es: "Martirio del imán Alí", pt: "Martírio do Imã Ali", ru: "Мученичество имама Али", zh: "伊玛目阿里殉难日", ja: "イマーム・アリー殉教の日", hi: "इमाम अली की शहादत", bn: "ইমাম আলীর শাহাদাত", id: "Syahidnya Imam Ali" },
};

const LOCALES = Object.keys(TITLES["عید نوروز"]) as (keyof Row)[];

// translations for a seeded title (one occasion or several joined by " · ");
// null when any part is not a known official title (an admin's own title)
export const holidayTitleTranslations = (title: string): Translations | null => {
  const parts = String(title || "")
    .split(" · ")
    .map((p) => p.trim())
    .filter(Boolean);
  if (!parts.length || parts.some((p) => !TITLES[p])) return null;
  const out: Translations = {};
  for (const l of LOCALES) out[l] = { title: parts.map((p) => TITLES[p][l]).join(" · ") };
  return out;
};
